### ISSUE TITLE
Update Project with Upstream HEAD

### ISSUE THREAD

**Issue by pavlovcik** [pavlovcik/uad-docs#13]
Ayo @ryzhak I could use your help to fix this issue if you're interested and available. 

The original code is forked from `transitive-bullshit` but our Ubiquity version diverged so far that its hard to keep the latest upstream changes in sync. Ideally if we can regularly merge in the upstream changes while preserving our Ubiquity fork changes that would be awesome! 

The main changes for Ubiquity are almost all cosmetic.

Theres two solutions:

1. Fix all the merge conflicts and hope that its stable
2. Fork the latest upstream code clean, and then manually add all the Ubiquity changes (seems more difficult.) Most of the time would be spent in making sure the TSX components have the correct hierarchy of elements, as well as `ubiquity.css` which houses most of the Ubiquity CSS changes.

_Originally posted by @pavlovcik in https://github.com/pavlovcik/uad-docs/issues/11#issuecomment-1330626597_

**Comment by ryzhak** [comment]
@pavlovcik 

so the task is to merge the `transitive-bullshit/nextjs-notion-starter-kit#main` branch into `pavlovcik/uad-docs#ubiquity` branch, right?

**Comment by pavlovcik** [comment]
I think that we should ideally 1. resolve the merge conflicts in the ubiquity branch, which is what this bounty is for. 
2. Consider setting up a GitHub action (I'm pretty sure this can be added from the GitHub Actions Marketplace) that automatically tries and fetch upstream when changes are introduced. In the future as soon as a merge conflict is found it may be more manageable to resolve if it's caught early.

**Comment by ryzhak** [comment]
got it, you can assign it to me

**Comment by pavlovcik** [comment]
Thanks for the speedy work! Can I get your DAI wallet address?

**Comment by ryzhak** [comment]
wallet: 0x165343c045a00770b61DbCa01956590cC6005666

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0xd13aaad1a9bf78b6cbaa88ff092fe5a042e73a44abb5fcd2d3005ca688981fe7
https://etherscan.io/tx/0x1c88b3b6be761ade96a84933d1deb7e0ce1cfbc6d2924ffa41010177281a89e1
