### ISSUE TITLE
Website Updating

### ISSUE THREAD

**Issue by pavlovcik** [pavlovcik/uad-docs#4]
I'm not exactly sure where the logic is to rescrape the notion source content, but I noticed that it doesn't seem to work anymore UNTIL a redeployment is made (it used to be automatic after a couple of page refreshes.)

Can you investigate @zequez ?

**Comment by Zequez** [comment]
I can give it a shot, see what I find.

**Comment by pavlovcik** [comment]
@transitive-bullshit if you have the secrets please share 🙏

**Comment by pavlovcik** [comment]
@Zequez https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/129#issuecomment-877979216

I was investigating in the source repo and this looks relevant to focus on

**Comment by pavlovcik** [comment]
This is considered bad practice because the endpoint to force redeploy is now public and anybody can invoke it. It's fine for the short term but we should not trust any critical information (e.g. smart contract addresses) on the website until this is properly fixed and this hack is removed.

https://vercel.com/docs/concepts/git/deploy-hooks#security

**Comment by marcomow** [comment]
Sir just store the hook url into an env var

**Comment by marcomow** [comment]
Sir just store the hook url into an env var

**Comment by marcomow** [comment]
To be 100% sure just create a new hook url first @pavlovcik

**Comment by pavlovcik** [comment]
Seems to have fixed itself. Not sure about this seemingly transient error.
